version: '2'

services:
    dbl:
        user: "1000:50"
        image: mariadb
        volumes:
            - "./.data/db:/var/lib/mysql"
            - ./mysql:/etc/mysql/conf.d
        ports:
            - 8084:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    memcache:
        image: memcached:alpine
        ports:
            - 11211:11211
    php56:
        build:
            context: php56-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../symfony:/var/www/symfony:cached
            - ../AGSLMS:/var/www/AGSLMS
            - ../PBOLMS:/var/www/PBOLMS
            - ../RCTLMS:/var/www/RCTLMS
            - ../uploads/gsdev/:/usr/local/gsdev
            - ../uploads/jobclass:/usr/local/jobclass:cached
            - ../uploads/pbodev:/usr/local/pbodev
            - ../uploads/rctdev:/usr/local/rctdev
    php7:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../ehs-admin:/var/www/ehs-admin
            - ../EHS4:/var/www/EHS4
            - ../EHS4/vendor:/var/www/EHS4/vendor:cached
            - ../EHS4/var:/var/www/EHS4/var:cached
            - ../uploads/ehs_stage:/usr/local/ehs
            - ../uploads/jobclass:/usr/local/jobclass
            - ../symfony:/var/www/symfony:cached
            - ../EHS:/var/www/EHS
    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php56
            - php7
        volumes:
            - ./logs/:/var/log
            - ./nginx/conf/sites-enabled:/etc/nginx/sites-enabled
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
