version: '2'

services:
    dbl:
        user: "1000:50"
        image: mariadb
        volumes:
            - "./.data/db:/var/lib/mysql"
            - ./mysql:/etc/mysql/conf.d
        ports:
            - 8084:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    memcache:
        image: memcached:alpine
        ports:
            - 11211:11211
    php7:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../bookrental:/var/www/bookrental
            - ../bookrental/vendor:/var/www/bookrental/vendor:cached
            - ../bookrental/var:/var/www/bookrental/var:cached
    nginx:
        build: nginx
        ports:
            - 8085:80
        volumes_from:
            - php7
        volumes:
            - ./logs/:/var/log
            - ./nginx/conf/sites-enabled:/etc/nginx/sites-enabled
    redis:
        image: redis:alpine
        ports:
            - 6379:6379
